num1 = int(input("Give me the first number: "))
num1 = int(num1)
num2 = int(input("Give me the second number: "))
num2 = int(num2)
print("Thank you!")
print(f"{num1} + {num2} = {num1 + num2}")
print(f"{num1} - {num2} = {num1 - num2}")
print(f"{num1} / {num2} = {num1 / num2}")
print(f"{num1} * {num2} = {num1 * num2}")

